/*
 * FormNuevoGesto.java
 *
 * Created on 19 de septiembre de 2007, 11:28 PM
 */

package Vista;

import Controlador.OperacionesGesto;
import Controlador.OperacionesTipo;
import Modelo.Gesto;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author  Jakolov
 */
public class FormEdicionGesto extends javax.swing.JInternalFrame {
    Gesto ges;
    OperacionesGesto opGesto;
    
    /** Creates new form FormNuevoGesto */
    public FormEdicionGesto() {
        initComponents();
    }

    public Gesto getGes() {
        return ges;
    }

    public void setGes(Gesto ges) {
        this.ges = ges;
        try{
            txtLetra.setText(ges.getLetra());
            txtNombre.setText(ges.getNombre());
            txtFactor.setValue(Integer.parseInt(ges.getFactor()));
            txtPorcentaje.setValue(Integer.parseInt(ges.getPct()));
            lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/edGesto.png")));
            lblTitulo.setText("Editar Gesto");
        }catch(Exception e){
            lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuGesto.png")));
            lblTitulo.setText("Nuevo Gesto");
            
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLetra = new javax.swing.JFormattedTextField();
        txtLetra = new javax.swing.JFormattedTextField(createFormatter("U"));
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comAceptar = new javax.swing.JButton();
        comCancelar = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFactor = new com.toedter.components.JSpinField();
        txtPorcentaje = new com.toedter.components.JSpinField();

        jLabel2.setText("Letra :");

        jLabel1.setText("Nombre :");

        comAceptar.setText("Aceptar");
        comAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comAceptarActionPerformed(evt);
            }
        });

        comCancelar.setText("Cancelar");
        comCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCancelarActionPerformed(evt);
            }
        });

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuTipo.png"))); // NOI18N
        lblIcono.setText("jLabel3");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 16));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nuevo Gesto");

        jLabel3.setText("Factor:");

        jLabel4.setText("Porcentaje:");

        txtFactor.setMinimum(1);
        txtFactor.setValue(1);

        txtPorcentaje.setMaximum(100);
        txtPorcentaje.setMinimum(0);
        txtPorcentaje.setValue(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblIcono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFactor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPorcentaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comCancelar)
                    .addComponent(comAceptar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comAceptarActionPerformed
        // TODO add your handling code here:
        try{
            String id = ges.getId();
            String letra = txtLetra.getText();
            String nombre = txtNombre.getText();
            String factor = String.valueOf(txtFactor.getValue());
            String pct = String.valueOf(txtPorcentaje.getValue());
            if(letra.length()== 1){
                opGesto = new OperacionesGesto(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
                opGesto.actualizarGesto(id, letra, nombre,factor,pct);
                borrar();
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"Debe especificar una letra no repetida para el Gesto");
            }
            
        }catch(Exception ex){
            opGesto = new OperacionesGesto(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
            String letra = txtLetra.getText();
            if(letra.length()== 1){
                opGesto.insertarGesto(letra, txtNombre.getText(),String.valueOf(txtFactor.getValue()),String.valueOf(txtPorcentaje.getValue()));
                borrar();
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"Debe especificar una letra no repetida para el Gesto");
            }
            
        }
    }//GEN-LAST:event_comAceptarActionPerformed

    private void comCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_comCancelarActionPerformed
    
        /**Crea un formateador para el formattedtextfield*/
    protected MaskFormatter createFormatter(String s) {
    MaskFormatter formatter = null;
    try {
        formatter = new MaskFormatter(s);
    } catch (java.text.ParseException exc) {
        System.err.println("formatter is bad: " + exc.getMessage());
        System.exit(-1);
    }
    return formatter;
    }
    
    private void borrar(){
        txtLetra.setText("");
        txtNombre.setText("");
        txtFactor.setValue(1);
        txtPorcentaje.setValue(10);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comAceptar;
    private javax.swing.JButton comCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblTitulo;
    private com.toedter.components.JSpinField txtFactor;
    private javax.swing.JFormattedTextField txtLetra;
    private javax.swing.JTextField txtNombre;
    private com.toedter.components.JSpinField txtPorcentaje;
    // End of variables declaration//GEN-END:variables
    
}
