package Vista;

import Controlador.OperacionesListaAcciones;

/*
 * FormListaAcciones.java
 *
 * Created on 1 de noviembre de 2007, 10:58
 */
import Modelo.Juego;
import java.awt.Rectangle;

/**
 *
 * @author  Jakolov
 */
public class FormListaAcciones extends javax.swing.JInternalFrame {

    private OperacionesListaAcciones opLista;
    private Juego j;

    /** Creates new form FormListaAcciones */
    public FormListaAcciones() {
        initComponents();

    }

    public void setJuego(Juego j) {
        this.j = j;
    }

    public void actualizar() {
        opLista = new OperacionesListaAcciones(FormPrincipal.getCon(), FormPrincipal.getOperacionesBasicas());
        opLista.setModelJugadores(j.getId().toString(), tblAcciones);
        lblTotalCodigos.setText(String.valueOf(opLista.getTotalAcciones(j.getId().toString())));
        this.mostrarUltimaCelda();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrTabla = new javax.swing.JScrollPane();
        tblAcciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTotalCodigos = new javax.swing.JLabel();

        setIconifiable(true);
        setResizable(true);
        setTitle("Acciones de Juego");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        scrTabla.setAutoscrolls(true);

        tblAcciones.setFont(new java.awt.Font("Arial", 0, 10));
        tblAcciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblAcciones.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblAcciones.setShowVerticalLines(false);
        scrTabla.setViewportView(tblAcciones);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel1.setText("Total Codigos:");

        lblTotalCodigos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalCodigos, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addComponent(lblTotalCodigos, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        opLista = new OperacionesListaAcciones(FormPrincipal.getCon(), FormPrincipal.getOperacionesBasicas());
        opLista.setModelJugadores(j.getId().toString(), tblAcciones);
        scrTabla.setViewportView(this.tblAcciones);
        lblTotalCodigos.setText(String.valueOf(opLista.getTotalAcciones(j.getId().toString())));
        this.mostrarUltimaCelda();
    }//GEN-LAST:event_formInternalFrameActivated
    public void mostrarUltimaCelda() {
        try {
            int row = this.tblAcciones.getRowCount() - 1;
            Rectangle rect = this.tblAcciones.getCellRect(row, 0, true);
            tblAcciones.scrollRectToVisible(rect);
            tblAcciones.clearSelection();
            tblAcciones.setRowSelectionInterval(row, row);
        } catch (Exception e) {
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTotalCodigos;
    private javax.swing.JScrollPane scrTabla;
    private javax.swing.JTable tblAcciones;
    // End of variables declaration//GEN-END:variables
}
