package Vista;

import Controlador.OperacionesRotacion;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formRotacion.java
 *
 * Created on 07-oct-2008, 16:42:06
 */
import Modelo.Juego;
import javax.swing.JOptionPane;

/**
 *
 * @author investigacion
 */
public class formRotacion extends javax.swing.JInternalFrame {
    private Juego juego;


    OperacionesRotacion ope ;
    
    /** Creates new form formRotacion */
    public formRotacion() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRotacion = new javax.swing.JTable();
        comCancelar = new javax.swing.JButton();
        comGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tblRotacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblRotacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PRO", null, null, null, null, null, null, null},
                {"OPP", null, null, null, null, null, null, null}
            },
            new String [] {
                "", "1", "2", "3", "4", "5", "6", "P"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRotacion);

        comCancelar.setText("Cancelar");
        comCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCancelarActionPerformed(evt);
            }
        });

        comGuardar.setText("Guardar");
        comGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comGuardarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rotacion");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Rotacion.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(comGuardar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comCancelar)
                    .addComponent(comGuardar))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-277)/2, (screenSize.height-178)/2, 277, 178);
    }// </editor-fold>//GEN-END:initComponents

    private void comCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_comCancelarActionPerformed

    private void comGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comGuardarActionPerformed
        // TODO add your handling code here:
        ope = new OperacionesRotacion(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas(),this.juego.getId(),this.juego.getCodPropio(),this.getJuego().getCodOpp());
        int eval = ope.RevisarAlineacion(tblRotacion);
        if(eval == 0){
            
        }else if(eval == 1){
            JOptionPane.showMessageDialog(null, "La Rotacion contiene numeros repetidos en alguno de los 2 equipos,No se puede procesar de esta manera");
        }else if(eval == 2){
            int sel = JOptionPane.showConfirmDialog(null, "Algunos de los jugadores en la rotacion no pertencen al equipo\n¿Desea continuar?","Alerta",JOptionPane.YES_NO_OPTION); 
            if(sel == JOptionPane.YES_OPTION){
                ope.guardarRotaciones(this.tblRotacion, String.valueOf(ope.getIdParcialActual()), this.juego.getCodPropio(), this.getJuego().getCodOpp());
                this.setVisible(false);
            }
        }else if(eval == 3){
            JOptionPane.showMessageDialog(null, "El numero del pasador debe estar dentro de la Rotacion definida");
        }else if(eval == 5){
            JOptionPane.showMessageDialog(null, "La rotacion contiene errores, revise que el pasador se encuentre en la rotacion");
        }else{
            ope.guardarRotaciones(this.tblRotacion, String.valueOf(ope.getIdParcialActual()), this.juego.getCodPropio(), this.getJuego().getCodOpp());
            this.setVisible(false);
        }
    }//GEN-LAST:event_comGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comCancelar;
    private javax.swing.JButton comGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRotacion;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the juego
     */
    public Juego getJuego() {
        return juego;
    }

    /**
     * @param juego the juego to set
     */
    public void setJuego(Juego juego) {
        this.juego = juego;
        this.tblRotacion.setValueAt(juego.getCodPropio(), 0, 0);
        this.tblRotacion.setValueAt(juego.getCodOpp(), 1, 0);
    }

}
