/*
 * FormNuevoTipo.java
 *
 * Created on 18 de septiembre de 2007, 02:52 PM
 */

package Vista;

import Controlador.OperacionesTipo;
import Modelo.Tipo;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author  Jakolov
 */
public class FormEdicionTipo extends javax.swing.JInternalFrame {
    private OperacionesTipo opTipo;
    private Tipo tip;


    
    /** Creates new form FormNuevoTipo */
    public FormEdicionTipo() {
        initComponents();
    }

    public void setTip(Tipo tip) {
        this.tip = tip;
        try{
            String let = tip.getLetra();
            String nom = tip.getNombre();
            txtLetra.setText(let);
            txtNombre.setText(nom);
            lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/edTipo.png")));
            lblTitulo.setText("Editar Jugador");
        }catch(Exception e){
            lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuTipo.png")));
            lblTitulo.setText("Nuevo Jugador");
        }
    }
   
    private void borrar(){
        txtLetra.setText("");
        txtNombre.setText("");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comCancelar = new javax.swing.JButton();
        comAceptar = new javax.swing.JButton();
        txtLetra = new javax.swing.JFormattedTextField();
        txtLetra = new javax.swing.JFormattedTextField(createFormatter("U"));
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setTitle("Tipo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        comCancelar.setText("Cancelar");
        comCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCancelarActionPerformed(evt);
            }
        });

        comAceptar.setText("Aceptar");
        comAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comAceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre :");

        jLabel2.setText("Letra :");

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuTipo.png"))); // NOI18N
        lblIcono.setText("jLabel3");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nuevo Tipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(comAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(lblIcono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comCancelar)
                    .addComponent(comAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_comCancelarActionPerformed

    private void comAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comAceptarActionPerformed
        // TODO add your handling code here:
        try{
            int id = tip.getIdTipo();
            String letra = txtLetra.getText();
            String nombre = txtNombre.getText();
            if(letra.length()== 1){
                opTipo.actualizarTipo(id, letra, nombre);
                borrar();
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"Debe especificar una letra no repetida para el tipo");
            }
             
        }catch(Exception ex){
            opTipo = new OperacionesTipo(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
            String letra = txtLetra.getText();
            if(letra.length()== 1){
                opTipo.insertarTipo(letra, txtNombre.getText());    
                borrar();
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"Debe especificar una letra no repetida para el tipo");
            }
            

        }
        
    }//GEN-LAST:event_comAceptarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        opTipo = new OperacionesTipo(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
        
    }//GEN-LAST:event_formInternalFrameActivated
    
    /**Crea un formateador para el formattedtextfield*/
    protected MaskFormatter createFormatter(String s) {
    MaskFormatter formatter = null;
    try {
        formatter = new MaskFormatter(s);
    } catch (java.text.ParseException exc) {
        System.err.println("formatter is bad: " + exc.getMessage());
        System.exit(-1);
    }
    return formatter;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comAceptar;
    private javax.swing.JButton comCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JFormattedTextField txtLetra;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    
}
