/*
 * FormTemporadas.java
 *
 * Created on 9 de agosto de 2007, 05:34 AM
 */

package Vista;
import java.util.LinkedList;
/**
 *
 * @author  Jakolov
 */
public class FormTemporadas extends javax.swing.JInternalFrame {
    LinkedList listaIndices;
    /** Creates new form FormTemporadas */
    public FormTemporadas() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comBorrar = new javax.swing.JButton();
        comCerrar = new javax.swing.JButton();
        comNuevaTemporada = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTemporadas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Temporadas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        comBorrar.setText("Borrar");
        comBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBorrarActionPerformed(evt);
            }
        });

        comCerrar.setText("Cerrar");
        comCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCerrarActionPerformed(evt);
            }
        });

        comNuevaTemporada.setText("Nueva");
        comNuevaTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNuevaTemporadaActionPerformed(evt);
            }
        });

        tblTemporadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTemporadas);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tmpGrande.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comNuevaTemporada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comBorrar, comCerrar, comNuevaTemporada});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comNuevaTemporada)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comCerrar)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-526)/2, (screenSize.height-367)/2, 526, 367);
    }// </editor-fold>//GEN-END:initComponents

private void comBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBorrarActionPerformed
    // TODO add your handling code here:
    try{
        
        int sel = tblTemporadas.getSelectedRow();
        if(sel >= 0){
            int sn = javax.swing.JOptionPane.showConfirmDialog(null,"Esta Seguro de Borrar "+tblTemporadas.getValueAt(sel, 0)+" y todo lo que contiene?"
                    , "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
            if (sn == javax.swing.JOptionPane.YES_OPTION){
                FormPrincipal.getCon().ejecutaStatement("Delete from Temporada Where idTemporada = "+listaIndices.get(sel)+"");
                //Actualizamos la tabla
                FormPrincipal.getOperacionesBasicas().setTableModelSQL(FormPrincipal.getCon(), "select nombre as Nombre ,fechaIni as Inicio, fechaFin as Fin, ano as anualidad from Temporada", tblTemporadas);
                listaIndices = FormPrincipal.getCon().devuelveColumnaEntero("Select idTemporada from Temporada", "idTemporada");
            }
        }
       
        
    }catch (Exception e){
        
    }
}//GEN-LAST:event_comBorrarActionPerformed

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    // TODO add your handling code here:
    
    FormPrincipal.getOperacionesBasicas().setTableModelSQL(FormPrincipal.getCon(), "select nombre as Nombre ,fechaIni as Inicio, fechaFin as Fin, ano as anualidad from Temporada", tblTemporadas);
    listaIndices = FormPrincipal.getCon().devuelveColumnaEntero("Select idTemporada from Temporada", "idTemporada");
}                                           

private void comNuevaTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNuevaTemporadaActionPerformed
    // TODO add your handling code here:
    FormPrincipal.getFormNuevaTemporada().setVisible(true);
}//GEN-LAST:event_comNuevaTemporadaActionPerformed

private void comCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCerrarActionPerformed
    // TODO add your handling code here:
    this.setVisible(false);
}//GEN-LAST:event_comCerrarActionPerformed

private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {                                         
    // TODO add your handling code here:
    FormPrincipal.getOperacionesBasicas().setTableModelSQL(FormPrincipal.getCon(), "select nombre as Nombre ,fechaIni as Inicio, fechaFin as Fin, ano as anualidad from Temporada", tblTemporadas);
    listaIndices = FormPrincipal.getCon().devuelveColumnaEntero("Select idTemporada from Temporada", "idTemporada");
}                                        
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comBorrar;
    private javax.swing.JButton comCerrar;
    private javax.swing.JButton comNuevaTemporada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTemporadas;
    // End of variables declaration//GEN-END:variables
    
}
