/*
 * FormEditarAceleradores.java
 *
 * Created on 22 de septiembre de 2007, 03:07 PM
 */

package Vista;

import Controlador.OperacionesAceleradores;
import Modelo.Acelerador;
import javax.swing.JOptionPane;

/**
 *
 * @author  Jakolov
 */
public class FormEdicionAceleradores extends javax.swing.JInternalFrame {
    OperacionesAceleradores opAcel ;
    Acelerador acelerador;
    /** Creates new form FormEditarAceleradores */
    public FormEdicionAceleradores() {
        initComponents();
    }

    public void setAcelerador(Acelerador acelerador) {
        this.acelerador = acelerador;
        try{
            txtAcelerador.setText(acelerador.getAcelerador());
            txtCodigo.setText(acelerador.getCodigo());
            txtDescripcion.setText(acelerador.getDescripcion());
            lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/edAcelerador.png")));
            lblTitulo.setText("Editar Acelerador");
        }catch(Exception e){
            lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuAcelerador.png")));
            lblTitulo.setText("Nuevo Acelerador");
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAcelerador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        comCancelar = new javax.swing.JButton();
        comAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        txtAcelerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAceleradorActionPerformed(evt);
            }
        });
        txtAcelerador.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtAceleradorPropertyChange(evt);
            }
        });
        txtAcelerador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAceleradorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAceleradorKeyTyped(evt);
            }
        });

        jLabel1.setText("Acelerador:");

        jLabel2.setText("Codigo:");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        comCancelar.setText("Cancelar");
        comCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCancelarActionPerformed(evt);
            }
        });

        comAceptar.setText("Aceptar");
        comAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comAceptarActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripcion:");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        txtDescripcion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDescripcionPropertyChange(evt);
            }
        });
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nuevo Acelerador");

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuAcelerador.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(comAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAcelerador, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIcono)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtAcelerador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblIcono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comCancelar)
                    .addComponent(comAceptar))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-289)/2, (screenSize.height-181)/2, 289, 181);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAceleradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAceleradorActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtAceleradorActionPerformed

    private void txtAceleradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAceleradorKeyPressed
        // TODO add your handling code here:
        String modificadores = evt.getKeyModifiersText(evt.getModifiers());
        String tecla = evt.getKeyText(evt.getKeyCode());
        if (modificadores.length() == 0){
            txtAcelerador.setText(tecla);
        }else if (tecla.equalsIgnoreCase(modificadores)){
            txtAcelerador.setText(modificadores);
        }else{
            txtAcelerador.setText(modificadores+"+"+tecla);
        }
        
    }//GEN-LAST:event_txtAceleradorKeyPressed

    private void txtAceleradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAceleradorKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtAceleradorKeyTyped

    private void txtAceleradorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtAceleradorPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_txtAceleradorPropertyChange

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtCodigoActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtDescripcionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDescripcionPropertyChange
        // TODO add your handling code here:
}//GEN-LAST:event_txtDescripcionPropertyChange

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_txtDescripcionKeyPressed

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_txtDescripcionKeyTyped

    private void comCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_comCancelarActionPerformed

    private void comAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comAceptarActionPerformed
        // TODO add your handling code here:
        try{
            String id = acelerador.getId();
            if(txtAcelerador.getText().length()>0 && txtCodigo.getText().length()>0){
            opAcel.ActualizaAcelerador(id, txtCodigo.getText(), txtAcelerador.getText(), txtDescripcion.getText());
            this.setVisible(false);
            borrar();    
            }else{
                JOptionPane.showMessageDialog(null, "El codigo y el acelerador son indispensables para la Actualizacion");
            }
            
        }catch(Exception e){
            if(txtAcelerador.getText().length()>0 && txtCodigo.getText().length()>0){
            opAcel.insertarAcelerador(txtCodigo.getText(), txtAcelerador.getText(), txtDescripcion.getText());
            this.setVisible(false);
            borrar();    
            }else{
                JOptionPane.showMessageDialog(null, "El codigo y el acelerador son indispensables para la creacion");
            }
            
        }
    }//GEN-LAST:event_comAceptarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        opAcel = new OperacionesAceleradores(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
    }//GEN-LAST:event_formInternalFrameActivated
    private void borrar(){
        txtCodigo.setText("");
        txtAcelerador.setText("");
        txtDescripcion.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comAceptar;
    private javax.swing.JButton comCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAcelerador;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
    
}
