/*
 * FormTorneos.java
 *
 * Created on 4 de septiembre de 2007, 04:06 PM
 */

package Vista;

/**
 *
 * @author  Jakolov
 */
import java.util.LinkedList;
import Controlador.OperacionesTorneo;
public class FormTorneos extends javax.swing.JInternalFrame {
    LinkedList listaIndices;
    OperacionesTorneo opTorneo;
    /** Creates new form FormTorneos */
    public FormTorneos() {
        listaIndices = new LinkedList();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTorneos = new javax.swing.JTable();
        comNuevoJugador = new javax.swing.JButton();
        comBorrar = new javax.swing.JButton();
        comCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Torneos");
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblTorneos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTorneos);

        comNuevoJugador.setText("Nuevo");
        comNuevoJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNuevoJugadorActionPerformed(evt);
            }
        });

        comBorrar.setText("Borrar");
        comBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBorrarActionPerformed(evt);
            }
        });

        comCerrar.setText("Cerrar");
        comCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCerrarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/toGrande.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comNuevoJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comNuevoJugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBorrar)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comCerrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-565)/2, (screenSize.height-347)/2, 565, 347);
    }// </editor-fold>//GEN-END:initComponents

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    // TODO add your handling code here:
    actualizaTabla();
    
}//GEN-LAST:event_formInternalFrameActivated

private void comCerrarActionPerformed(java.awt.event.ActionEvent evt) {    // TODO add your handling code here://GEN-FIRST:event_comCerrarActionPerformed
    this.setVisible(false);
}//GEN-LAST:event_comCerrarActionPerformed

private void comNuevaTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNuevaTemporadaActionPerformed
    // TODO add your handling code here:
    FormPrincipal.getFormNuevoTorneo().setVisible(true);
}//GEN-LAST:event_comNuevaTemporadaActionPerformed

private void comBorrarActionPerformed(java.awt.event.ActionEvent evt) {    // TODO add your handling code here://GEN-FIRST:event_comBorrarActionPerformed
    try{
        int sel = tblTorneos.getSelectedRow();
        if ( sel >= 0 ){
            opTorneo.borrarTorneo(listaIndices.get(sel).toString());
            actualizaTabla();
        }
    }catch(Exception e){
        e.printStackTrace();
    }
}//GEN-LAST:event_comBorrarActionPerformed

private void comNuevoJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNuevoJugadorActionPerformed
    // TODO add your handling code here:
    FormPrincipal.getFormNuevoTorneo().setVisible(true);
}//GEN-LAST:event_comNuevoJugadorActionPerformed
    
private void actualizaTabla(){
   opTorneo = new OperacionesTorneo(FormPrincipal.getCon(), FormPrincipal.getOperacionesBasicas());
   opTorneo.setModeloTorneo(tblTorneos);
   listaIndices = opTorneo.getListaIndices();
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comBorrar;
    private javax.swing.JButton comCerrar;
    private javax.swing.JButton comNuevoJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTorneos;
    // End of variables declaration//GEN-END:variables
    
}
