/*
 * FormListaJugadores.java
 *
 * Created on 15 de octubre de 2007, 11:18 PM
 */

package Vista;

import Controlador.OperacionesListaJugadores;
import Modelo.Juego;
import javax.swing.JOptionPane;

/**
 *
 * @author  jakolov
 */
public class FormListaJugadores extends javax.swing.JInternalFrame {
    private Juego juego ;
    OperacionesListaJugadores opLista;
    /** Creates new form FormListaJugadores */
    public FormListaJugadores() {
        initComponents();
    }

    public Juego getJuego() {
        return juego;
    }

    public void setJuego(Juego juego) {
        this.juego = juego;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpEquipos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJugadoresPropio = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJugadoresOpp = new javax.swing.JTable();
        comCerrar = new javax.swing.JButton();
        comBorrar = new javax.swing.JButton();
        comNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Lista de Jugadores");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblJugadoresPropio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblJugadoresPropio);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpEquipos.addTab("Propio", jPanel1);

        tblJugadoresOpp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblJugadoresOpp);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpEquipos.addTab("Oponente", jPanel2);

        comCerrar.setText("Cerrar"); // NOI18N
        comCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCerrarActionPerformed(evt);
            }
        });

        comBorrar.setText("Borrar"); // NOI18N
        comBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBorrarActionPerformed(evt);
            }
        });

        comNuevo.setText("Nuevo"); // NOI18N
        comNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbpEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                        .addComponent(comCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comBorrar)
                    .addComponent(comNuevo)
                    .addComponent(comCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNuevoActionPerformed
        // TODO add your handling code here:
        FormPrincipal.getFormEdicionJugador().setJug(null);
        FormPrincipal.getFormEdicionJugador().setCodJuego(juego.getId().toString());
        FormPrincipal.getFormEdicionJugador().setSwOp(1);
        if(tbpEquipos.getSelectedIndex() == 0){
            FormPrincipal.getFormEdicionJugador().setIdEquipo(juego.getCodPropio());
        }else{
            FormPrincipal.getFormEdicionJugador().setIdEquipo(juego.getCodOpp());
        }
        FormPrincipal.getFormEdicionJugador().setVisible(true);
}//GEN-LAST:event_comNuevoActionPerformed

    private void comCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_comCerrarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        opLista = new OperacionesListaJugadores(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
        String codPropio = juego.getCodPropio();
        String codOpp = juego.getCodOpp();
        int idJuego = juego.getId();
        opLista.setModelListaJugadores(codOpp, String.valueOf(idJuego), tblJugadoresOpp);
        opLista.setModelListaJugadores(codPropio, String.valueOf(idJuego), tblJugadoresPropio);
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void comBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBorrarActionPerformed
        // TODO add your handling code here:
        // borrarmos solo el jugador del juego, no del equipo.
        // hacemos un delete de la tabla jugjue usando como filtro el codigo del jugador
        opLista = new OperacionesListaJugadores(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
        javax.swing.JTable tbl;
        if(tbpEquipos.getSelectedIndex() == 0){
            tbl = this.tblJugadoresPropio;
        }else{
            tbl = this.tblJugadoresOpp;
        }
        String codJugador = tbl.getValueAt(tbl.getSelectedRow(),1).toString();
        int sel = JOptionPane.showConfirmDialog(null, "Esta Seguro de Quitar al Jugador con el Codigo "+codJugador);
        if(sel ==  JOptionPane.OK_OPTION){
            opLista.borrarJugadorJuego(codJugador, juego.getId().toString());
            actualizar();
        }
        
}//GEN-LAST:event_comBorrarActionPerformed
    private void actualizar(){
        opLista = new OperacionesListaJugadores(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
        String codPropio = juego.getCodPropio();
        String codOpp = juego.getCodOpp();
        int idJuego = juego.getId();
        opLista.setModelListaJugadores(codOpp, String.valueOf(idJuego), tblJugadoresOpp);
        opLista.setModelListaJugadores(codPropio, String.valueOf(idJuego), tblJugadoresPropio);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comBorrar;
    private javax.swing.JButton comCerrar;
    private javax.swing.JButton comNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblJugadoresOpp;
    private javax.swing.JTable tblJugadoresPropio;
    private javax.swing.JTabbedPane tbpEquipos;
    // End of variables declaration//GEN-END:variables
    
}
