/*
 * FormNuevoEquipo.java
 *
 * Created on 9 de agosto de 2007, 03:05 AM
 */

package Vista;
import Controlador.OperacionesBasicas;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
/**
 *
 * @author  Jakolov
 */
public class FormNuevoEquipo extends javax.swing.JInternalFrame {
    private OperacionesBasicas operacionesBasicas;
    private MaskFormatter mascara;
    /** Creates new form FormNuevoEquipo */
    public FormNuevoEquipo() {
        operacionesBasicas = new OperacionesBasicas();
        initComponents();
        operacionesBasicas.centrar(this);
                
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txtNombre = new javax.swing.JTextField();
    comCancelar = new javax.swing.JButton();
    comAceptar = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    txtCodigo = new javax.swing.JFormattedTextField();
    txtCodigo = new javax.swing.JFormattedTextField(createFormatter("UUU"));
    lblIcono = new javax.swing.JLabel();

    setClosable(true);
    setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("COD:");

    jTextField2.setText("jTextField1");

    jLabel2.setText("Nombre:");

    comCancelar.setText("Cancelar");
    comCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comCancelarActionPerformed(evt);
      }
    });

    comAceptar.setText("Aceptar");
    comAceptar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comAceptarActionPerformed(evt);
      }
    });

    jLabel3.setBackground(new java.awt.Color(0, 0, 204));
    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(0, 0, 102));
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("Nuevo Equipo");

    lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuEquipo.png"))); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(15, 15, 15)
            .addComponent(jLabel1))
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(comAceptar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(comCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblIcono, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
        .addGap(369, 369, 369)
        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(3, 3, 3)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel1)))
              .addComponent(lblIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(comCancelar)
              .addComponent(comAceptar)))
          .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-324)/2, (screenSize.height-204)/2, 324, 204);
  }// </editor-fold>//GEN-END:initComponents

    private void comCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCancelarActionPerformed
// TODO: Agrege su codigo aqui:
        operacionesBasicas.cerrarFormulario(this);
    }//GEN-LAST:event_comCancelarActionPerformed

    private void comAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comAceptarActionPerformed
        // TODO add your handling code here:
        
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        if(codigo.length()== 3){
            try{
                FormPrincipal.getCon().ejecutaStatement("insert into Equipo(codigo,nombre) values('" + codigo + "','" + nombre + "')");
                borrar();
                this.setVisible(false);
            }catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(null, "No se ha podido crear este equipo,Revise que el codigo no se repita");
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(null,"Codigo vacio para el equipo, Debe escoger un codigo");
        }
    }//GEN-LAST:event_comAceptarActionPerformed
    
    /**Crea un formateador para el formattedtextfield*/ 
    protected MaskFormatter createFormatter(String s) {
    MaskFormatter formatter = null;
    try {
        formatter = new MaskFormatter(s);
    } catch (java.text.ParseException exc) {
        System.err.println("formatter is bad: " + exc.getMessage());
        System.exit(-1);
    }
    return formatter;
    }
    
    /**Borra los campos usados en la creacion del equipo*/
    private void borrar(){
        txtCodigo.setText("");
        try{
            txtCodigo.commitEdit();
        }catch(Exception e){
            
        }
        
        txtNombre.setText("");
    }

    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton comAceptar;
  private javax.swing.JButton comCancelar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JLabel lblIcono;
  private javax.swing.JFormattedTextField txtCodigo;
  private javax.swing.JTextField txtNombre;
  // End of variables declaration//GEN-END:variables
    
}
