
/*
 * FormControladorDeJuego.java
 *
 * Created on 24 de octubre de 2007, 03:31 PM
 */
package Vista;

import Controlador.OperacionesControladorJuego;
import Modelo.Accion;
import Modelo.Juego;
import javax.swing.JOptionPane;

/**
 *
 * @author  jakolov
 */
public class FormControladorDeJuego extends javax.swing.JInternalFrame {

    /**
     * @return the opeJuego
     */
    public static OperacionesControladorJuego getOpeJuego() {
        return opeJuego;
    }

    /**
     * @param aOpeJuego the opeJuego to set
     */
    public static void setOpeJuego(OperacionesControladorJuego aOpeJuego) {
        opeJuego = aOpeJuego;
    }

    //Identificadores del Juego
    private String idJuego;
    private String codPropio;
    private String codOpp;
    private Juego juego;
    private static OperacionesControladorJuego opeJuego;

    /** Creates new form FormControladorDeJuego */
    public FormControladorDeJuego() {
        initComponents();

    }

    /**Establece  el juego */
    public void setJuego(Juego ju) {
        this.juego = ju;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigo.getText();

        Accion[] a = getOpeJuego().getAcciones(codigo);
        for (int i = 0; i < a.length; i++) {
            getOpeJuego().guardarAccion(a[i]);
            //si es la ultima de las acciones
            if (i == a.length - 1) {
                //evaluamos el fin de rally
                getOpeJuego().cambioDeRally(a[i]);
            }
        }
        setOpeJuego(new OperacionesControladorJuego(FormPrincipal.getCon(), FormPrincipal.getOperacionesBasicas(), this.juego.getCodPropio(), this.juego.getCodOpp(), String.valueOf(this.juego.getId())));
        FormPrincipal.getFormListaAcciones().actualizar();
        FormPrincipal.getFormJuego().setJuego(this.juego);
        txtCodigo.setText("");
}//GEN-LAST:event_txtCodigoActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        setOpeJuego(new OperacionesControladorJuego(FormPrincipal.getCon(), FormPrincipal.getOperacionesBasicas(), this.juego.getCodPropio(), this.juego.getCodOpp(), String.valueOf(this.juego.getId())));
        FormPrincipal.getFormJuego().setJuego(this.juego);
        FormPrincipal.getFormAnalisisZonas().setJuego(this.juego);
        FormPrincipal.getFormAnalisisDireccion().setJuego(this.juego);
        FormPrincipal.getMenAnalisis().setEnabled(true);
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        FormPrincipal.getFormListaAcciones().setVisible(false);
        FormPrincipal.getFormListaJugadores().setVisible(false);
        FormPrincipal.getFormJuego().setVisible(false);
        FormPrincipal.getMenAnalisis().setEnabled(false);
    }//GEN-LAST:event_formInternalFrameClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
