/*
 * FormTipos.java
 *
 * Created on 18 de septiembre de 2007, 05:02 AM
 */

package Vista;
import Controlador.OperacionesTipo;
import Modelo.Tipo;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author  Jakolov
 */
public class FormTipos extends javax.swing.JInternalFrame {
    private OperacionesTipo opTipo;
    private LinkedList listaIndices;
    private LinkedList listaTipCre;
    /** Creates new form FormTipos */
    public FormTipos() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipos = new javax.swing.JTable();
        comNuevo = new javax.swing.JButton();
        comBorrar = new javax.swing.JButton();
        comEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Tipos de Gesto");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTipos);

        comNuevo.setText("Nuevo");
        comNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNuevoActionPerformed(evt);
            }
        });

        comBorrar.setText("Borrar");
        comBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBorrarActionPerformed(evt);
            }
        });

        comEditar.setText("Editar");
        comEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comEditarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tiGrande.png"))); // NOI18N

        comCerrar.setText("Cerrar");
        comCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(comCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comCerrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-319)/2, (screenSize.height-254)/2, 319, 254);
    }// </editor-fold>//GEN-END:initComponents

    private void comNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNuevoActionPerformed
        // TODO add your handling code here:
        FormPrincipal.getFormNuevoTipo().setTip(null);
        FormPrincipal.getFormNuevoTipo().setVisible(true);
    }//GEN-LAST:event_comNuevoActionPerformed

    private void comBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBorrarActionPerformed
        // TODO add your handling code here:
        try{
            int sel = tblTipos.getSelectedRow();
            if (sel > -1 && Integer.parseInt(listaTipCre.get(sel).toString()) == 0) {
                opTipo = new OperacionesTipo(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
                opTipo.borrarTipo(listaIndices.get(sel).toString());
                
                opTipo = new OperacionesTipo(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
                opTipo.setModeloTipos(tblTipos);
                listaIndices = opTipo.getListaIndices();
                listaTipCre = opTipo.getListaIndices();
                
            }else if(Integer.parseInt(listaTipCre.get(sel).toString()) == 1){
                JOptionPane.showMessageDialog(null, "No esta permitido borrar este tipo, solo editarlo");
            }
            
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_comBorrarActionPerformed

    private void comEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comEditarActionPerformed
        // TODO add your handling code here:
        try{
            listaIndices = opTipo.getListaIndices();
            int sel = tblTipos.getSelectedRow();
            if(sel >= 0){
                Tipo tip = new Tipo(Integer.valueOf(listaIndices.get(sel).toString()),tblTipos.getValueAt(sel, 1).toString(),tblTipos.getValueAt(sel, 0).toString());
                FormPrincipal.getFormNuevoTipo().setTip(tip);
                FormPrincipal.getFormNuevoTipo().setVisible(true);
            }
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_comEditarActionPerformed
    
    private void comCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_comCerrarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        opTipo = new OperacionesTipo(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
        opTipo.setModeloTipos(tblTipos);
        listaIndices = opTipo.getListaIndices();
        listaTipCre = opTipo.getListaTipCre();
    }//GEN-LAST:event_formInternalFrameActivated
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comBorrar;
    private javax.swing.JButton comCerrar;
    private javax.swing.JButton comEditar;
    private javax.swing.JButton comNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTipos;
    // End of variables declaration//GEN-END:variables
    
}
