/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormAnalisisDireccion.java
 *
 * Created on 14-oct-2008, 22:25:27
 */
package Vista;

import Controlador.OperacionesAnalisisDireccion;
import Modelo.Juego;
import Modelo.PanelDirecciones;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;

/**
 *
 * @author Jakolov
 */
public class FormAnalisisDireccion extends javax.swing.JInternalFrame {
    private Juego juego;
    PanelDirecciones pnlDir;
    OperacionesAnalisisDireccion ope;
    JComponent vista;
    /** Creates new form FormAnalisisDireccion */
    public FormAnalisisDireccion() {
        initComponents();
        pnlDir = new PanelDirecciones();
        pnlAnalisis.setLayout(null);
        vista = pnlDir.getComponenteVistaDirecciones(new LinkedList(),new LinkedList(),new LinkedList());
        vista.setBounds(0, 0, 475, 308);
        pnlAnalisis.add(vista);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboEquipo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboParciales = new javax.swing.JComboBox();
        cboGestos = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cboP = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cboZona = new javax.swing.JComboBox();
        comCerrar = new javax.swing.JButton();
        comActualizar = new javax.swing.JButton();
        pnlAnalisis = new javax.swing.JPanel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Analisis de Direcciones");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        cboEquipo.setFont(new java.awt.Font("Tahoma", 0, 10));

        jLabel1.setText("Equipo:");

        jLabel2.setText("SET:");

        cboParciales.setFont(new java.awt.Font("Tahoma", 0, 10));

        cboGestos.setFont(new java.awt.Font("Tahoma", 0, 10));
        cboGestos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Saque", "Ataque" }));

        jLabel3.setText("Gesto:");

        cboP.setFont(new java.awt.Font("Tahoma", 0, 10));
        cboP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO", "P", "aP" }));

        jLabel4.setText("Condicion:");

        cboZona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguna", "en 1", "en 2", "en 3", "en 4", "en 5", "en 6" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboParciales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboEquipo, 0, 53, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboZona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cboGestos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboParciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboGestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        comCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cerrar.png"))); // NOI18N
        comCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCerrarActionPerformed(evt);
            }
        });

        comActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Rotacion.png"))); // NOI18N
        comActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAnalisisLayout = new javax.swing.GroupLayout(pnlAnalisis);
        pnlAnalisis.setLayout(pnlAnalisisLayout);
        pnlAnalisisLayout.setHorizontalGroup(
            pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        pnlAnalisisLayout.setVerticalGroup(
            pnlAnalisisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comActualizar, 0, 0, Short.MAX_VALUE)
                            .addComponent(comCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comActualizarActionPerformed
        // TODO add your handling code here:
        ope = new OperacionesAnalisisDireccion(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
        ope.cargarIdParciales(this.juego.getId().toString());
        String condicion = ope.getCondicionSql(cboEquipo, cboParciales, cboGestos, cboP, cboZona);
        //System.out.println(condicion);
        this.pnlDir.getEscena().removeChildren();
        vista = pnlDir.getComponenteVistaDirecciones(ope.getSalidas(condicion), ope.getDestinos(condicion),ope.getValores(condicion));
        vista.setBounds(0, 0, 475, 308);
        pnlAnalisis.add(vista);
        pnlAnalisis.repaint();
}//GEN-LAST:event_comActualizarActionPerformed

    private void comCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_comCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboEquipo;
    private javax.swing.JComboBox cboGestos;
    private javax.swing.JComboBox cboP;
    private javax.swing.JComboBox cboParciales;
    private javax.swing.JComboBox cboZona;
    private javax.swing.JButton comActualizar;
    private javax.swing.JButton comCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlAnalisis;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the juego
     */
    public Juego getJuego() {
        return juego;
    }

    /**
     * @param juego the juego to set
     */
    public void setJuego(Juego juego) {
        this.juego = juego;
        ope = new OperacionesAnalisisDireccion(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
        this.cargarEquipos();
        this.cargarParciales();
    }
    
    private void cargarEquipos() {
        this.cboEquipo.setModel(new DefaultComboBoxModel(ope.getCodigosEquipos(getJuego().getId().toString())));
    }
    
    private void cargarParciales() {
        this.cboParciales.setModel(new DefaultComboBoxModel(ope.getParciales(getJuego().getId().toString())));
    }
}
