/*
 * FormAceleradores.java
 *
 * Created on 20 de septiembre de 2007, 05:08 PM
 */

package Vista;

import Controlador.OperacionesAceleradores;
import Modelo.Acelerador;
import java.util.LinkedList;

/**
 *
 * @author  Jakolov
 */
public class FormAceleradores extends javax.swing.JInternalFrame {
    OperacionesAceleradores opAcel ;
    LinkedList listaIndices ;
    /** Creates new form FormAceleradores */
    public FormAceleradores() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comNuevo = new javax.swing.JButton();
        comBorrar = new javax.swing.JButton();
        comEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAceleradores = new javax.swing.JTable();

        setTitle("Aceleradores");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        comNuevo.setText("Nuevo");
        comNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNuevoActionPerformed(evt);
            }
        });

        comBorrar.setText("Borrar");
        comBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBorrarActionPerformed(evt);
            }
        });

        comEditar.setText("Editar");
        comEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comEditarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/acGrande.png"))); // NOI18N

        comCerrar.setText("Cerrar");
        comCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCerrarActionPerformed(evt);
            }
        });

        tblAceleradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblAceleradores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comNuevo))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comEditar)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(comCerrar)))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-508)/2, (screenSize.height-337)/2, 508, 337);
    }// </editor-fold>//GEN-END:initComponents

    private void comNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNuevoActionPerformed
        // TODO add your handling code here:
        FormPrincipal.getFormEdicionAceleradores().setAcelerador(null);
        FormPrincipal.getFormEdicionAceleradores().setVisible(true);
    }//GEN-LAST:event_comNuevoActionPerformed

    private void comBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBorrarActionPerformed
        // TODO add your handling code here:
        try{
            int sel = tblAceleradores.getSelectedRow();
            if (sel > -1){
                opAcel.borrarAcelerador(listaIndices.get(sel).toString());
                opAcel.setModeloAceleradores(tblAceleradores);
                listaIndices = opAcel.getListaIndices();
            }else{
                
            }
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_comBorrarActionPerformed

    private void comEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comEditarActionPerformed
        // TODO add your handling code here:
        try{
            int sel = tblAceleradores.getSelectedRow();
            if(sel >= 0){
                Acelerador ac = new Acelerador(listaIndices.get(sel).toString(),tblAceleradores.getValueAt(sel, 0).toString(),tblAceleradores.getValueAt(sel, 2).toString(),tblAceleradores.getValueAt(sel, 1).toString());
                FormPrincipal.getFormEdicionAceleradores().setAcelerador(ac);
                FormPrincipal.getFormEdicionAceleradores().setVisible(true);
            }
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_comEditarActionPerformed

    private void comCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_comCerrarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        opAcel = new OperacionesAceleradores(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
        opAcel.setModeloAceleradores(tblAceleradores);
        listaIndices = opAcel.getListaIndices();
    }//GEN-LAST:event_formInternalFrameActivated
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comBorrar;
    private javax.swing.JButton comCerrar;
    private javax.swing.JButton comEditar;
    private javax.swing.JButton comNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAceleradores;
    // End of variables declaration//GEN-END:variables
    
}
