/*
 * FormEdicionJugador.java
 *
 * Created on 12 de septiembre de 2007, 02:09 PM
 */

package Vista;
import javax.swing.text.MaskFormatter;
import Controlador.OperacionesJugador;
import Modelo.Jugador;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.JOptionPane;
/**
 *
 * @author  Jakolov
 */
public class FormEdicionJugador extends javax.swing.JInternalFrame {
    private String idEquipo;
    private OperacionesJugador opJugador;
    private LinkedList listaNumeros;
    private Jugador jug;
    private int swOp = 0;
    private String codJuego;
    
    /** Creates new form FormEdicionJugador */
    public FormEdicionJugador() {
        initComponents();
    }

    public void setCodJuego(String codJuego) {
        this.codJuego = codJuego;
    }
    
    public int getSwOp() {
        return swOp;
    }

    public void setSwOp(int swOp) {
        this.swOp = swOp;
    }
    
    
    public void setIdEquipo(String idEquipo) {
        this.idEquipo = idEquipo;
    }

    public void setJug(Jugador jug) {
        this.jug = jug;
        try{
            String cod = jug.getCodigo();
            String nom = jug.getNombre();
            String num = jug.getNumero();
            String est = jug.getEstatura();
            String pes = jug.getPeso();
            txtCodigo.setText(cod);
            txtNombre.setText(nom);
            txtNumero.setText(num);
            txtEstatura.setText(est);
            txtPeso.setText(pes);
            lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/EditarJugadorPequeno.png")));
            lblTitulo.setText("Editar Jugador");
        }catch(Exception e){
            lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/NuevoJugadorPequeno.png")));
            lblTitulo.setText("Nuevo Jugador");
        }
    }
    
    protected MaskFormatter createFormatter(String s) {
        MaskFormatter formatter = null;
            try {
                formatter = new MaskFormatter(s);
            } catch (java.text.ParseException exc) {
                System.err.println("formatter is bad: " + exc.getMessage());
                System.exit(-1);
            }
        return formatter;
    }
    protected MaskFormatter createFormatterNumero(){
        MaskFormatter formatter = null;
            try {
                formatter = new MaskFormatter("**");
                formatter.setValidCharacters("0123456789 ");
            } catch (java.text.ParseException exc) {
                System.err.println("formatter is bad: " + exc.getMessage());
                System.exit(-1);
            }
        return formatter;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JFormattedTextField();
        txtNumero = new javax.swing.JFormattedTextField(createFormatterNumero());
        txtCodigo = new javax.swing.JFormattedTextField();
        txtCodigo = new javax.swing.JFormattedTextField(createFormatter("UUU-UUU"));
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEstatura = new javax.swing.JFormattedTextField();
        txtPeso = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        comCancelar = new javax.swing.JButton();
        comAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Numero");

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        txtEstatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstaturaActionPerformed(evt);
            }
        });

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        jLabel4.setText("Estatura");

        jLabel5.setText("Peso");

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/NuevoJugadorPequeno.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 28));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nuevo Jugador");

        comCancelar.setText("Cancelar");
        comCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCancelarActionPerformed(evt);
            }
        });

        comAceptar.setText("Aceptar");
        comAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPeso))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(comAceptar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comCancelar)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcono)
                    .addComponent(lblTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comCancelar)
                    .addComponent(comAceptar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-374)/2, (screenSize.height-208)/2, 374, 208);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtNumeroActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtCodigoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtNombreActionPerformed

    private void txtEstaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstaturaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtEstaturaActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtPesoActionPerformed

    private void comAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comAceptarActionPerformed
        // TODO add your handling code here:
        if(swOp == 0){
            try{
                String codb = jug.getCodigo();
                opJugador = new OperacionesJugador(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
                if(txtNumero.getText().length()>0 && txtCodigo.getText().replace(" ", "").length()==7){
                    if(this.conteoNumeroEnEquipo(idEquipo, txtNumero.getText()) == 0 || this.conteoNumeroEnEquipo(idEquipo, txtNumero.getText()) == 1 && txtNumero.getText().equalsIgnoreCase( jug.getNumero() )){
                        opJugador.actualizarJugador(codb,txtNumero.getText(), txtCodigo.getText(), txtNombre.getText(), txtEstatura.getText(), txtPeso.getText());
                        this.setVisible(false);
                    }else{
                        JOptionPane.showMessageDialog(null, "Ya Existe un jugador con este Número");
                    }

                    
                }else{
                    JOptionPane.showMessageDialog(null, "Los campos nombre y codigo son indispensables");
                    this.setVisible(false);
                }
            }catch(Exception e){
                opJugador = new OperacionesJugador(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
                if(txtNumero.getText().length()>0 && txtCodigo.getText().replace(" ", "").length()==7){
                    if(this.conteoNumeroEnEquipo(idEquipo, txtNumero.getText()) == 0){
                        opJugador.insertarJugador(txtNumero.getText(), txtCodigo.getText(), txtNombre.getText(), txtEstatura.getText(), txtPeso.getText(), idEquipo);
                        this.setVisible(false);
                    }else{
                        JOptionPane.showMessageDialog(null, "Ya Existe un jugador con este Número");
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Los campos nombre y codigo son indispensables");
                }
            }
        }else{
                opJugador = new OperacionesJugador(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
                System.out.println(txtCodigo.getText());
                if(txtNumero.getText().length()>0 && txtCodigo.getText().replace(" ", "").length()==7){
                    if(this.conteoNumeroEnEquipo(idEquipo, txtNumero.getText()) == 0){
                        opJugador.insertarJugador(txtNumero.getText(), txtCodigo.getText(), txtNombre.getText(), txtEstatura.getText(), txtPeso.getText(), idEquipo);
                        opJugador.insertarJugadorJuego(txtCodigo.getText(), codJuego);
                        this.setVisible(false);
                        this.setSwOp(0);
                        this.setCodJuego("");
                    }else{
                        JOptionPane.showMessageDialog(null, "Ya Existe un jugador con este Número");
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Los campos nombre y codigo son indispensables");
                }
        }
        
        borrar();//GEN-LAST:event_comAceptarActionPerformed
}                                          

    private void comCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCancelarActionPerformed
        // TODO add your handling code here:
        borrar();
        this.setVisible(false);
}//GEN-LAST:event_comCancelarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameActivated
    private void borrar(){
        txtNumero.setText("");
        txtCodigo.setText("");
        txtNombre.setText("");
        txtEstatura.setText("");
        txtPeso.setText("");
    }
    private int conteoNumeroEnEquipo(String idEquipo, String numero){
        int result = 0;
        opJugador = new OperacionesJugador(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
        LinkedList listaNumeros = opJugador.getListaNumeros(idEquipo);
        Iterator i = listaNumeros.iterator();
        while(i.hasNext()){
            String num = i.next().toString();
            if(num.equals(numero)){
                result++;
            }
        }
        return result;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comAceptar;
    private javax.swing.JButton comCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JFormattedTextField txtCodigo;
    private javax.swing.JFormattedTextField txtEstatura;
    private javax.swing.JFormattedTextField txtNombre;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JFormattedTextField txtPeso;
    // End of variables declaration//GEN-END:variables
    
}
