/*
 * FormDetallesEquipo.java
 *
 * Created on 8 de septiembre de 2007, 04:35 AM
 */

package Vista;

import java.util.LinkedList;
import Controlador.OperacionesEquipo;
import Controlador.OperacionesDetalleEquipo;
import Modelo.Jugador;
/**
 *
 * @author  Jakolov
 */
public class FormDetallesEquipo extends javax.swing.JInternalFrame {
    private String idEquipo;
    private OperacionesEquipo opEquipo;
    private OperacionesDetalleEquipo opDet;
    private LinkedList listaIndices;
    /** Creates new form FormDetallesEquipo */
    public FormDetallesEquipo() {
        
        initComponents();
    }
    
    public void setidEquipo(String id){
        this.idEquipo = id;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblJugadores = new javax.swing.JTable();
        comBorrar = new javax.swing.JButton();
        comNuevoJugador = new javax.swing.JButton();
        comCerrar = new javax.swing.JButton();
        comEditar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEntrenador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAsistente = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Detalles de Equipo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblJugadores);

        comBorrar.setText("Borrar");
        comBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBorrarActionPerformed(evt);
            }
        });

        comNuevoJugador.setText("Nuevo");
        comNuevoJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNuevoJugadorActionPerformed(evt);
            }
        });

        comCerrar.setText("Cerrar");
        comCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCerrarActionPerformed(evt);
            }
        });

        comEditar.setText("Editar");
        comEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comEditarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Entrenador:");

        jLabel2.setText("Asist.:");

        jLabel4.setText("Ciudad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(txtEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(txtAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4)
                .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/DetalleEquipo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comNuevoJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comNuevoJugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comEditar)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comCerrar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBorrarActionPerformed
        // TODO add your handling code here:
        try{
            int sel = tblJugadores.getSelectedRow();
            if(sel >= 0){
                int sn = javax.swing.JOptionPane.showConfirmDialog(null,"Esta Seguro de Borrar "+tblJugadores.getValueAt(sel, 1)
                        , "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
                if (sn == javax.swing.JOptionPane.YES_OPTION){
                    opDet.borrarJugador(listaIndices.get(sel).toString());
                    opDet.setModelJugadores(idEquipo, tblJugadores);
                    listaIndices = opDet.getListaJugadores(idEquipo);
                }
            }
        }catch (Exception e){
            
        }
        
    }//GEN-LAST:event_comBorrarActionPerformed

    private void comNuevoJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNuevoJugadorActionPerformed
        // TODO add your handling code here:
        FormPrincipal.getFormEdicionJugador().setJug(null);
        FormPrincipal.getFormEdicionJugador().setIdEquipo(idEquipo);
        FormPrincipal.getFormEdicionJugador().setVisible(true);
}//GEN-LAST:event_comNuevoJugadorActionPerformed

    private void comCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCerrarActionPerformed
        // TODO add your handling code here:
        int sel = javax.swing.JOptionPane.showConfirmDialog(null, "Desea Guardar los Cambios al Equipo?","Confirmar",javax.swing.JOptionPane.YES_NO_OPTION);
        if (sel == javax.swing.JOptionPane.YES_OPTION){
            //guardamos el equipo y los jugadores
            //1. guardamos los datos del equipo
            String entrenador = txtEntrenador.getText();
            String asistente = txtAsistente.getText();
            String ciudad = txtCiudad.getText();
            
            opDet.setEntrenador(idEquipo, entrenador);
            opDet.setAsistente(idEquipo, asistente);
            opDet.setCiudad(idEquipo, ciudad);
        }
        this.setVisible(false);
    }//GEN-LAST:event_comCerrarActionPerformed

    private void comEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comEditarActionPerformed
        // TODO add your handling code here:
        try{
            int sel = tblJugadores.getSelectedRow();
            if(sel >= 0){
                Jugador jug = new Jugador();
                jug.setNumero(tblJugadores.getValueAt(sel, 0).toString());
                jug.setCodigo(tblJugadores.getValueAt(sel, 1).toString());
                jug.setNombre(tblJugadores.getValueAt(sel, 2).toString());
                jug.setEstatura(tblJugadores.getValueAt(sel, 3).toString());
                jug.setPeso(tblJugadores.getValueAt(sel, 4).toString());
                FormPrincipal.getFormEdicionJugador().setJug(jug);
                FormPrincipal.getFormEdicionJugador().setIdEquipo(idEquipo);
                FormPrincipal.getFormEdicionJugador().setVisible(true);
                
               
            }
        }catch (Exception e){
            
        }
}//GEN-LAST:event_comEditarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
            opDet = new OperacionesDetalleEquipo(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
            setTitle("Detalle de : " + opDet.getNombre(idEquipo));
            opDet.setModelJugadores(idEquipo, tblJugadores);
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
            opDet = new OperacionesDetalleEquipo(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
            txtEntrenador.setText(opDet.getEntrenador(idEquipo));
            txtAsistente.setText(opDet.getAsistente(idEquipo));
            txtCiudad.setText(opDet.getCiudad(idEquipo));
            listaIndices = opDet.getListaJugadores(idEquipo);
    }//GEN-LAST:event_formInternalFrameOpened

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comBorrar;
    private javax.swing.JButton comCerrar;
    private javax.swing.JButton comEditar;
    private javax.swing.JButton comNuevoJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJugadores;
    private javax.swing.JTextField txtAsistente;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtEntrenador;
    // End of variables declaration//GEN-END:variables
    
}
