/*
 * FormGestos.java
 *
 * Created on 18 de septiembre de 2007, 04:42 AM
 */

package Vista;

import Controlador.OperacionesGesto;
import Modelo.Gesto;
import java.util.LinkedList;

/**
 *
 * @author  Jakolov
 */
public class FormGestos extends javax.swing.JInternalFrame {
    OperacionesGesto opGesto;
    private LinkedList listaIndices;
    /** Creates new form FormGestos */
    public FormGestos() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestos = new javax.swing.JTable();
        comNuevo = new javax.swing.JButton();
        comBorrar = new javax.swing.JButton();
        comEditar = new javax.swing.JButton();
        comCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Gestos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblGestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblGestos);

        comNuevo.setText("Nuevo");
        comNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNuevoActionPerformed(evt);
            }
        });

        comBorrar.setText("Borrar");
        comBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBorrarActionPerformed(evt);
            }
        });

        comEditar.setText("Editar");
        comEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comEditarActionPerformed(evt);
            }
        });

        comCerrar.setText("Cerrar");
        comCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCerrarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/geGrande.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comEditar)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(comCerrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-449)/2, (screenSize.height-310)/2, 449, 310);
    }// </editor-fold>//GEN-END:initComponents

    private void comNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNuevoActionPerformed
        // TODO add your handling code here:
        FormPrincipal.getFormEdicionGesto().setGes(null);
        FormPrincipal.getFormEdicionGesto().setVisible(true);
}//GEN-LAST:event_comNuevoActionPerformed

    private void comBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBorrarActionPerformed
        // TODO add your handling code here:
        try{
            int sel = tblGestos.getSelectedRow();
            if (sel > -1){
                opGesto = new OperacionesGesto(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
                opGesto.borrarGesto(listaIndices.get(sel).toString());
                opGesto.setModeloGestos(tblGestos);
                listaIndices = opGesto.getListaIndices();
            }else{
                
            }
        }catch(Exception ex){
            
        }
}//GEN-LAST:event_comBorrarActionPerformed

    private void comEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comEditarActionPerformed
        // TODO add your handling code here:
        try{
            int sel = tblGestos.getSelectedRow();
            if(sel >= 0){
                Gesto ges = new Gesto();
                ges.setLetra(tblGestos.getValueAt(sel, 0).toString());
                ges.setNombre(tblGestos.getValueAt(sel, 1).toString());
                ges.setFactor(tblGestos.getValueAt(sel, 2).toString());
                ges.setPct(tblGestos.getValueAt(sel, 3).toString());
                ges.setId(listaIndices.get(sel).toString());
                FormPrincipal.getFormEdicionGesto().setGes(ges);
                FormPrincipal.getFormEdicionGesto().setVisible(true);
            }
        }catch (Exception e){
            
        }
}//GEN-LAST:event_comEditarActionPerformed

    private void comCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_comCerrarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        opGesto = new OperacionesGesto(FormPrincipal.getCon(),FormPrincipal.getOperacionesBasicas());
        opGesto.setModeloGestos(tblGestos);
        listaIndices = opGesto.getListaIndices();
    }//GEN-LAST:event_formInternalFrameActivated
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comBorrar;
    private javax.swing.JButton comCerrar;
    private javax.swing.JButton comEditar;
    private javax.swing.JButton comNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGestos;
    // End of variables declaration//GEN-END:variables
    
}
