/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewCommand.java
 *
 * Created on Jun 26, 2011, 1:36:31 PM
 */
package org.pagbel.statistics.ui.game;

import org.pagbel.statistics.action.GameAction;
import org.pagbel.statistics.engine.ActionGenerator;
import org.pagbel.statistics.engine.ActionProcessor;
import org.pagbel.statistics.engine.CompoundActionGenerator;
import org.pagbel.statistics.engine.CompoundActionProcessor;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author apagano
 */
public class CommandEditor extends javax.swing.JInternalFrame {
  
  @Autowired
  ActionGenerator actionGenerator;
  
  @Autowired
  ActionProcessor actionProcessor;
  
  @Autowired
  CompoundActionGenerator compoundGenerator;

  /** Creates new form NewCommand */
  public CommandEditor() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    txtCommand = new javax.swing.JTextField();

    setTitle("CommandEditor");

    txtCommand.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
    txtCommand.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtCommandActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, txtCommand, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(txtCommand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommandActionPerformed
    String command = txtCommand.getText().trim();
    
    if( command.contains(".") ){
      GameAction[] actions = compoundGenerator.generate( command );
      //Process actions
      actionProcessor.processAction( actions[0], Boolean.FALSE );
      actionProcessor.processAction( actions[1], Boolean.TRUE );
    }else if(command.startsWith("<<")){
      //TODO: Handle game commands ( PTS, SERVICE, ROTATION, CHANGE)
      System.out.println("Here we should handle ingame commands");
    }else{
      GameAction action = actionGenerator.generate(command);
      actionProcessor.processAction(action, Boolean.TRUE);
    }
    
    txtCommand.setText("");
  }//GEN-LAST:event_txtCommandActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField txtCommand;
  // End of variables declaration//GEN-END:variables
}
