/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DefineRotations.java
 *
 * Created on Jun 25, 2011, 9:02:30 PM
 */
package org.pagbel.statistics.ui.game;

import org.pagbel.statistics.ui.MainWindow;
import org.pagbel.statistics.engine.GameHolder;
import org.pagbel.statistics.game.Game;
import org.pagbel.statistics.game.Partial;
import org.pagbel.statistics.hibernate.DatabaseOperator;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author apagano
 */
public class DefineRotations extends javax.swing.JInternalFrame {

  @Autowired
  GameHolder gameHolder;
  @Autowired
  DatabaseOperator databaseOperator;
  @Autowired
  MainWindow mainWindow;

  /** Creates new form DefineRotations */
  public DefineRotations() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    lbl4 = new javax.swing.JLabel();
    lbl3 = new javax.swing.JLabel();
    lbl6 = new javax.swing.JLabel();
    lbl5 = new javax.swing.JLabel();
    lbl7 = new javax.swing.JLabel();
    lbl8 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    btnSaveRotation = new javax.swing.JButton();
    pnlRotation = new javax.swing.JPanel();
    txtSZ1 = new javax.swing.JTextField();
    txtSZ2 = new javax.swing.JTextField();
    txtSZ3 = new javax.swing.JTextField();
    txtSZ4 = new javax.swing.JTextField();
    txtSZ5 = new javax.swing.JTextField();
    txtSZ6 = new javax.swing.JTextField();
    txtP = new javax.swing.JTextField();
    txtOZ1 = new javax.swing.JTextField();
    txtOZ2 = new javax.swing.JTextField();
    txtOZ3 = new javax.swing.JTextField();
    txtOZ4 = new javax.swing.JTextField();
    txtOZ5 = new javax.swing.JTextField();
    txtOZ6 = new javax.swing.JTextField();
    txtaP = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    lblSelfCode = new javax.swing.JLabel();
    lblOpponentCode = new javax.swing.JLabel();
    btnCancel = new javax.swing.JButton();

    setTitle("Define Rotations");
    addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
      public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
        DefineRotations.this.internalFrameOpened(evt);
      }
      public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
      }
    });
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        onShown(evt);
      }
    });
    addInputMethodListener(new java.awt.event.InputMethodListener() {
      public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
        internalFrameActivated(evt);
      }
      public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
      }
    });

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel2.setLayout(new java.awt.GridLayout(1, 7, 10, 0));

    lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbl4.setText("1");
    jPanel2.add(lbl4);

    lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbl3.setText("2");
    jPanel2.add(lbl3);

    lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbl6.setText("3");
    jPanel2.add(lbl6);

    lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbl5.setText("4");
    jPanel2.add(lbl5);

    lbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbl7.setText("5");
    jPanel2.add(lbl7);

    lbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbl8.setText("6");
    jPanel2.add(lbl8);

    jLabel1.setText("P");
    jPanel2.add(jLabel1);

    btnSaveRotation.setText("Save");
    btnSaveRotation.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSaveRotationActionPerformed(evt);
      }
    });

    pnlRotation.setBackground(new java.awt.Color(204, 204, 204));
    pnlRotation.setLayout(new java.awt.GridLayout(2, 7));
    pnlRotation.add(txtSZ1);
    pnlRotation.add(txtSZ2);
    pnlRotation.add(txtSZ3);
    pnlRotation.add(txtSZ4);
    pnlRotation.add(txtSZ5);

    txtSZ6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtSZ6ActionPerformed(evt);
      }
    });
    pnlRotation.add(txtSZ6);
    pnlRotation.add(txtP);
    pnlRotation.add(txtOZ1);
    pnlRotation.add(txtOZ2);
    pnlRotation.add(txtOZ3);
    pnlRotation.add(txtOZ4);
    pnlRotation.add(txtOZ5);
    pnlRotation.add(txtOZ6);
    pnlRotation.add(txtaP);

    jPanel3.setLayout(new java.awt.GridLayout(2, 0, 5, 5));

    lblSelfCode.setBackground(new java.awt.Color(0, 102, 255));
    lblSelfCode.setForeground(new java.awt.Color(255, 255, 255));
    lblSelfCode.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lblSelfCode.setText("SelfTeam : ");
    lblSelfCode.setOpaque(true);
    jPanel3.add(lblSelfCode);

    lblOpponentCode.setBackground(new java.awt.Color(255, 51, 51));
    lblOpponentCode.setForeground(new java.awt.Color(255, 255, 255));
    lblOpponentCode.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lblOpponentCode.setText("Opponent : ");
    lblOpponentCode.setOpaque(true);
    jPanel3.add(lblOpponentCode);

    btnCancel.setText("Cancel");
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .add(btnCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(btnSaveRotation))
          .add(layout.createSequentialGroup()
            .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlRotation, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(4, 4, 4)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(pnlRotation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(btnSaveRotation)
          .add(btnCancel))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void internalFrameActivated(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_internalFrameActivated
  }//GEN-LAST:event_internalFrameActivated

  private void setSelfRotation(String[] rotation, String passer) {
    if (rotation!= null && rotation.length == 6) {
      this.txtSZ1.setText(rotation[0]);
      this.txtSZ2.setText(rotation[1]);
      this.txtSZ3.setText(rotation[2]);
      this.txtSZ4.setText(rotation[3]);
      this.txtSZ5.setText(rotation[4]);
      this.txtSZ6.setText(rotation[5]);
    }

    this.txtP.setText(passer);
  }

  private void setOpponentRotation(String[] rotation, String passer) {
    if (rotation!= null && rotation.length == 6) {
      this.txtOZ1.setText(rotation[0]);
      this.txtOZ2.setText(rotation[1]);
      this.txtOZ3.setText(rotation[2]);
      this.txtOZ4.setText(rotation[3]);
      this.txtOZ5.setText(rotation[4]);
      this.txtOZ6.setText(rotation[5]);
    }
    this.txtaP.setText(passer);
  }

  private void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_internalFrameOpened
    Game currentGame = gameHolder.getCurrentGame();
    this.lblSelfCode.setText(currentGame.getSelfCode() + " : ");
    this.lblOpponentCode.setText(currentGame.getOpponentCode() + " : ");
  }//GEN-LAST:event_internalFrameOpened

  private void btnSaveRotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRotationActionPerformed
    String[] selfRotation = this.getSelfRotation();
    String[] opponentRotation = this.getOpponentRotation();
    Partial currentPartial = gameHolder.getCurrentGame().getCurrentPartial();

    currentPartial.setSelfTeamRotation(selfRotation);
    currentPartial.setOpponentTeamRotation(opponentRotation);
    currentPartial.setSelfPasser(this.txtP.getText());
    currentPartial.setOpponentPasser(this.txtaP.getText());

    this.databaseOperator.saveOrUpdate(gameHolder.getCurrentGame());
    this.dispose();
    mainWindow.uptateStatus();
  }//GEN-LAST:event_btnSaveRotationActionPerformed

  private String[] getSelfRotation() {
    String z1 = this.txtSZ1.getText().length() > 0 ? this.txtSZ1.getText() : "00";
    String z2 = this.txtSZ2.getText().length() > 0 ? this.txtSZ2.getText() : "00";
    String z3 = this.txtSZ3.getText().length() > 0 ? this.txtSZ3.getText() : "00";
    String z4 = this.txtSZ4.getText().length() > 0 ? this.txtSZ4.getText() : "00";
    String z5 = this.txtSZ5.getText().length() > 0 ? this.txtSZ5.getText() : "00";
    String z6 = this.txtSZ6.getText().length() > 0 ? this.txtSZ6.getText() : "00";

    return new String[]{z1, z2, z3, z4, z5, z6};
  }

  private String[] getOpponentRotation() {
    String z1 = this.txtOZ1.getText().length() > 0 ? this.txtOZ1.getText() : "00";
    String z2 = this.txtOZ2.getText().length() > 0 ? this.txtOZ2.getText() : "00";
    String z3 = this.txtOZ3.getText().length() > 0 ? this.txtOZ3.getText() : "00";
    String z4 = this.txtOZ4.getText().length() > 0 ? this.txtOZ4.getText() : "00";
    String z5 = this.txtOZ5.getText().length() > 0 ? this.txtOZ5.getText() : "00";
    String z6 = this.txtOZ6.getText().length() > 0 ? this.txtOZ6.getText() : "00";

    return new String[]{z1, z2, z3, z4, z5, z6};
  }

  private void txtSZ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSZ6ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtSZ6ActionPerformed

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    this.dispose();
  }//GEN-LAST:event_btnCancelActionPerformed

  private void onShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_onShown
    Game game = gameHolder.getCurrentGame();
    Partial partial = game.getCurrentPartial();

    String[] selfRotation = partial.getSelfTeamRotation();
    String selfPasser = partial.getSelfPasser();
    String[] opponentRotation = partial.getOpponentTeamRotation();
    String opponentPasser = partial.getOpponentPasser();

    this.setSelfRotation(selfRotation, selfPasser);
    this.setOpponentRotation(opponentRotation, opponentPasser);
  }//GEN-LAST:event_onShown
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnSaveRotation;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JLabel lbl3;
  private javax.swing.JLabel lbl4;
  private javax.swing.JLabel lbl5;
  private javax.swing.JLabel lbl6;
  private javax.swing.JLabel lbl7;
  private javax.swing.JLabel lbl8;
  private javax.swing.JLabel lblOpponentCode;
  private javax.swing.JLabel lblSelfCode;
  private javax.swing.JPanel pnlRotation;
  private javax.swing.JTextField txtOZ1;
  private javax.swing.JTextField txtOZ2;
  private javax.swing.JTextField txtOZ3;
  private javax.swing.JTextField txtOZ4;
  private javax.swing.JTextField txtOZ5;
  private javax.swing.JTextField txtOZ6;
  private javax.swing.JTextField txtP;
  private javax.swing.JTextField txtSZ1;
  private javax.swing.JTextField txtSZ2;
  private javax.swing.JTextField txtSZ3;
  private javax.swing.JTextField txtSZ4;
  private javax.swing.JTextField txtSZ5;
  private javax.swing.JTextField txtSZ6;
  private javax.swing.JTextField txtaP;
  // End of variables declaration//GEN-END:variables
}
