/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ActionList.java
 *
 * Created on Jun 26, 2011, 10:49:59 PM
 */
package org.pagbel.statistics.ui.action;

import java.awt.Color;
import java.awt.Component;
import java.awt.Rectangle;
import java.util.Enumeration;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import org.pagbel.statistics.action.GameAction;
import org.pagbel.statistics.engine.GameHolder;
import org.pagbel.statistics.game.Game;
import org.pagbel.statistics.hibernate.DatabaseOperator;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.hibernate3.HibernateTemplate;
import org.pagbel.statistics.ui.MainWindow;

/**
 *
 * @author apagano
 */
public class ActionList extends javax.swing.JInternalFrame {

  @Autowired
  private DatabaseOperator databaseOperator;
  @Autowired
  private GameHolder gameHolder;
  @Autowired
  private MainWindow mainWindow;
  @Autowired
  private EditAction editActionIF;
  private List<GameAction> actions;

  /** Creates new form ActionList */
  public ActionList() {
    initComponents();
  }

  public void reloadActionList() {
    Game currentGame = gameHolder.getCurrentGame();
    actions = databaseOperator.find("from GameAction where game = ? ", currentGame);
    this.reloadTableData();
    lblActionCount.setText(String.valueOf(actions.size()) + " Codes");
    this.fixTableColumn();
  }

  private void reloadTableData() {
    Object[] arrAction = actions.toArray();
    Object[][] tableData = new Object[arrAction.length][5];

    for (int i = 0; i < arrAction.length; i++) {
      GameAction ga = (GameAction) arrAction[i];
      tableData[i][0] = String.valueOf(i + 1);
      tableData[i][1] = ga.getCompleteCode();
      
      if( ga.getWrongCode() == Boolean.FALSE ){
        tableData[i][4] = ga.getService() ? "S" : "R";
        tableData[i][2] = ga.getSelfPasserPosition().toString();
        tableData[i][3] = ga.getOpponentPasserPosition().toString();
      }else{
        tableData[i][4] = "x";
        tableData[i][2] = "x";
        tableData[i][3] = "x";
      }
    }

    tblActions.setModel(new javax.swing.table.DefaultTableModel(tableData, new String[]{"#", "CODE", "P", "aP", "S/R"}));
    //Scrolling to last cell
    this.scrollToCell(arrAction.length - 1, 0);
  }

  private void fixTableColumn() {
    TableColumn col = this.tblActions.getColumnModel().getColumn(2);
    col.setPreferredWidth(20);
    col = this.tblActions.getColumnModel().getColumn(3);
    col.setPreferredWidth(20);
    col = this.tblActions.getColumnModel().getColumn(4);
    col.setPreferredWidth(20);
    col = this.tblActions.getColumnModel().getColumn(0);
    col.setPreferredWidth(20);
    col = this.tblActions.getColumnModel().getColumn(1);
    col.setPreferredWidth(100);
  }

  public void scrollToCell(int row, int column) {
    if (row > 0) {
      Rectangle rect = tblActions.getCellRect(row, column, true);
      scrollRectToVisible(rect);
      tblActions.clearSelection();
      tblActions.setRowSelectionInterval(row, row);
      tblActions.scrollRectToVisible(tblActions.getCellRect(row, column, true));
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblActions = new JTable(){
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column){
                Component c = super.prepareRenderer(renderer, row, column);

                if (!isRowSelected(row)){
                    c.setBackground(getBackground());
                    int modelRow = convertRowIndexToModel(row);
                    String wrong = (String)getModel().getValueAt(modelRow, 3);
                    if ("x".equals(wrong)){
                        c.setBackground(Color.RED);
                    }
                }

                return c;
            }
        };
        lblActionCount = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnFilter = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDeleteAction = new javax.swing.JButton();

        setTitle("Actions");

        tblActions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblActions);

        lblActionCount.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        lblActionCount.setText("XX Codes");

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        btnFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/statistics/ui/icons/filter.gif"))); // NOI18N
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        jPanel1.add(btnFilter);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/statistics/ui/icons/edit.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);

        btnDeleteAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/statistics/ui/icons/action_delete.png"))); // NOI18N
        btnDeleteAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteAction);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(lblActionCount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 358, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblActionCount, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btnDeleteActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionActionPerformed

    int selectedIndex = this.tblActions.getSelectedRow();

    if (selectedIndex != -1) {
      GameAction selectedAction = this.actions.get(selectedIndex);
      databaseOperator.delete(selectedAction);
      this.reloadActionList();
      JOptionPane.showInternalMessageDialog(mainWindow.getDesktopPane(), "Action Deleted");
    } else {
      JOptionPane.showInternalMessageDialog(mainWindow.getDesktopPane(), "Please select the action you would like to delete");
    }
  }//GEN-LAST:event_btnDeleteActionActionPerformed

  private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnFilterActionPerformed

  private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    int selectedIndex = this.tblActions.getSelectedRow();

    if (selectedIndex != -1) {
      GameAction selectedAction = this.actions.get(selectedIndex);
      editActionIF.setAction(selectedAction);
      mainWindow.showEditAction();
    } else {
      JOptionPane.showInternalMessageDialog(mainWindow.getDesktopPane(), "Please select the action you would like to delete");
    }
  }//GEN-LAST:event_btnEditActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAction;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFilter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActionCount;
    private javax.swing.JTable tblActions;
    // End of variables declaration//GEN-END:variables
}
