/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateTeam.java
 *
 * Created on Jun 25, 2011, 10:54:03 AM
 */
package org.pagbel.statistics.ui.structure;


import org.pagbel.statistics.hibernate.DatabaseOperator;
import org.pagbel.statistics.structure.Team;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author apagano
 */
public class CreateTeam extends javax.swing.JInternalFrame {
  
  
  private Team selectedTeam;

  @Autowired
  DatabaseOperator databaseOperator;
  
  @Autowired
  TeamList teamListIF;

  
  /** Creates new form CreateTeam */
  public CreateTeam() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txtTeamCode = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txtTeamName = new javax.swing.JTextField();
    btnCreate = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();
    lblIcono = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();

    setClosable(true);
    setTitle("New Team");

    jLabel1.setText("Code");

    txtTeamCode.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtTeamCodeActionPerformed(evt);
      }
    });

    jLabel2.setText("Name");

    btnCreate.setText("Create");
    btnCreate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCreateActionPerformed(evt);
      }
    });

    btnCancel.setText("Cancel");

    lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/statistics/ui/icons/Eq.png"))); // NOI18N

    jLabel3.setBackground(new java.awt.Color(0, 0, 204));
    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
    jLabel3.setForeground(new java.awt.Color(0, 0, 102));
    jLabel3.setText("New Team");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
              .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .add(txtTeamCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnCancel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnCreate))
              .add(layout.createSequentialGroup()
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                  .add(layout.createSequentialGroup()
                    .add(jLabel2)
                    .add(141, 141, 141)
                    .add(lblIcono))
                  .add(txtTeamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 211, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
          .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(12, 12, 12)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
          .add(layout.createSequentialGroup()
            .add(jLabel3)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
              .add(jLabel1)
              .add(jLabel2)))
          .add(lblIcono))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(txtTeamCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(txtTeamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(btnCreate)
          .add(btnCancel))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtTeamCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeamCodeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtTeamCodeActionPerformed

  public void setSelectedTeam( Team team ){
    this.selectedTeam = team;
    this.txtTeamCode.setText(team.getCode());
    this.txtTeamName.setText(team.getName());
  }
  

  private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    
    Team team = selectedTeam == null ? new Team() : selectedTeam;
    team.setCode(this.txtTeamCode.getText());
    team.setName(this.txtTeamName.getText());
    databaseOperator.saveOrUpdate( team );
    this.setVisible(false);
    this.selectedTeam = null;
    //Reloading data lo show new tam on list :)
    teamListIF.reloadTableData();
  }//GEN-LAST:event_btnCreateActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnCreate;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel lblIcono;
  private javax.swing.JTextField txtTeamCode;
  private javax.swing.JTextField txtTeamName;
  // End of variables declaration//GEN-END:variables
}
