/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerList.java
 *
 * Created on Jul 16, 2011, 1:06:13 PM
 */
package org.pagbel.statistics.ui.structure;

import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import org.pagbel.statistics.hibernate.DatabaseOperator;
import org.pagbel.statistics.structure.Player;
import org.pagbel.statistics.structure.Team;
import org.pagbel.statistics.ui.MainWindow;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author apagano
 */
public class PlayerList extends javax.swing.JInternalFrame {

  Object[] teams;
  Object[] players ;
  
  private Team selectedTeam;
  @Autowired
  DatabaseOperator databaseOperator;
  @Autowired
  MainWindow mainWindow;
  @Autowired
  CreatePlayer createPlayerIF;
  
  

  /** Creates new form PlayerList */
  public PlayerList() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    cboTeams = new javax.swing.JComboBox();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblPlayers = new javax.swing.JTable();
    btnLoad = new javax.swing.JButton();
    btnEdit = new javax.swing.JButton();
    btnDelete = new javax.swing.JButton();
    btnCreate = new javax.swing.JButton();
    btnClose = new javax.swing.JButton();

    setClosable(true);
    setTitle("Player List");
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentShown(java.awt.event.ComponentEvent evt) {
        onShown(evt);
      }
    });

    jLabel1.setText("Team");

    cboTeams.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    cboTeams.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cboTeamsActionPerformed(evt);
      }
    });

    tblPlayers.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(tblPlayers);

    btnLoad.setText("Load");
    btnLoad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLoadActionPerformed(evt);
      }
    });

    btnEdit.setText("Edit");
    btnEdit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditActionPerformed(evt);
      }
    });

    btnDelete.setText("Delete");
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });

    btnCreate.setText("Create");
    btnCreate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCreateActionPerformed(evt);
      }
    });

    btnClose.setText("Close");
    btnClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCloseActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, 0, 0, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
            .add(jLabel1)
            .add(18, 18, 18)
            .add(cboTeams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 331, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
          .add(btnClose, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .add(btnLoad, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
          .add(btnEdit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
          .add(btnDelete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
          .add(btnCreate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1)
          .add(cboTeams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(btnLoad))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
          .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 232, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(layout.createSequentialGroup()
            .add(btnEdit)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(btnDelete)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(btnCreate)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(btnClose)))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    Player selectedPlayer = getSelectedPlayer();
    if( selectedPlayer !=  null ){
      databaseOperator.delete(selectedPlayer);
      this.reloadTableData();
    } else {
      JOptionPane.showInternalMessageDialog(mainWindow.getDesktopPane(), "Please select the player you want to delete.");
    }
  }//GEN-LAST:event_btnDeleteActionPerformed

  private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    createPlayerIF.setSelectedTeam(selectedTeam);
    this.mainWindow.showCreatePlayer();

  }//GEN-LAST:event_btnCreateActionPerformed

  private Player getSelectedPlayer(){
    Player result = null;
    Integer index = tblPlayers.getSelectedRow();
    
    if( index != -1){
      result = (Player)players[ index ];
    }
    
    return result;
  }
  private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
    this.dispose();
  }//GEN-LAST:event_btnCloseActionPerformed

  private void onShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_onShown
    teams = databaseOperator.find("from Team").toArray();

    cboTeams.setModel(new javax.swing.DefaultComboBoxModel(teams));

    if (teams.length > 0 && selectedTeam == null) {
      selectedTeam = (Team) teams[0];
    } else if (selectedTeam != null) {
      cboTeams.setSelectedItem(selectedTeam);
    }

    reloadTableData();

  }//GEN-LAST:event_onShown

  private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    Player selectedPlayer = getSelectedPlayer();
    if( selectedPlayer !=  null ){
      createPlayerIF.setSelectedPlayer(selectedPlayer);
      createPlayerIF.setSelectedTeam(selectedTeam);
      this.mainWindow.showCreatePlayer();
    }else{
      JOptionPane.showInternalMessageDialog(mainWindow.getDesktopPane(), "Please select the player you want to edit.");
    }
  }//GEN-LAST:event_btnEditActionPerformed

  private void cboTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTeamsActionPerformed
    selectedTeam = (Team) cboTeams.getSelectedItem();
    reloadTableData();
  }//GEN-LAST:event_cboTeamsActionPerformed

  private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
    selectedTeam = (Team) cboTeams.getSelectedItem();
    reloadTableData();
  }//GEN-LAST:event_btnLoadActionPerformed

  public void reloadTableData() {
    if (selectedTeam != null) {
      players = databaseOperator.find("from Player p where p.team = ?", selectedTeam).toArray();
      Object[][] tableData = new Object[players.length][2];

      for (int i = 0; i < players.length; i++) {
        Player g = (Player) players[i];
        tableData[i][0] = g.getNumber();
        tableData[i][1] = g.getName();

      }

      tblPlayers.setModel(new javax.swing.table.DefaultTableModel(tableData, new String[]{"#", "Name"}));
      fixTableColumns();
    }
  }

  private void fixTableColumns() {
    TableColumn col = tblPlayers.getColumnModel().getColumn(0);
    col.setPreferredWidth(20);
    col = tblPlayers.getColumnModel().getColumn(1);
    col.setPreferredWidth(400);
  }

  public Team getSelectedTeam() {
    return selectedTeam;
  }

  public void setSelectedTeam(Team selectedTeam) {
    this.selectedTeam = selectedTeam;
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnClose;
  private javax.swing.JButton btnCreate;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnEdit;
  private javax.swing.JButton btnLoad;
  private javax.swing.JComboBox cboTeams;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tblPlayers;
  // End of variables declaration//GEN-END:variables
}
